#!/bin/bash

SCRIPT_DIR="$(dirname -- "$0")"
PROJECT_DIR="$PWD"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
ENV_FILE="$SCRIPT_DIR/.env"

docker compose -f "$COMPOSE_FILE" \
			   --env-file "$ENV_FILE" \
			   --project-directory "$PROJECT_DIR" \
			   up ansys
