version: '3.8'

services:
  ansys:
    image: ansys:2022R1
    container_name: ansys
    build:
      context: .
      target: runtime
      args:
        - USR=${USR}
        - GRP=${GRP}
      shm_size: 4gb
      labels:
        hr.unizg.fsb.maintainer: "milovic.ph@gmail.com"
        hr.unizg.fsb.description: "Ansys | Engineering Simulation Software"
        hr.unizg.fsb.ansys-version: "2022 R1"
    entrypoint: ["/bin/bash", "-c"]
    command: ["/opt/ansys/ansys_inc/v221/Framework/bin/Linux64/runwb2"]
    runtime: nvidia
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      #- /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${SUDO_USER}/.Xauthority:/home/${USR}/.Xauthority:rw
      - .:/home/${USR}/workspace/
      # only for testing, the final image will contain the binaries
      - /opt/ansys:/opt/ansys
