version: '3.8'

services:
  ansys:
    image: ansys
    build:
      context: .
      target: runtime
      args:
        - USR=${USR}
        - GRP=${GRP}
        - ANSYS_SERVER_HOSTNAME=${ANSYS_SERVER_HOSTNAME}
    entrypoint: ["/bin/bash", "-c"]
    command: ["/usr/ansys_inc/v221/Framework/bin/Linux64/runwb2"]
    runtime: nvidia
    shm_size: 4gb
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    user: ${USR}
    group_add:
      - ${GRP}
    working_dir: /home/${USR}/workspace
    network_mode: host
    volumes:
      #- /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${RUNTIME_USER}/.Xauthority:/home/${USR}/.Xauthority:rw
      - .:/home/${USR}/workspace/
